imports:
  - { resource: services.yaml }

services:
  App\Gateway\UserGateway: '@App\Adapter\Doctrine\Repository\UserRepository'
  App\Gateway\AdminGateway: '@App\Adapter\Doctrine\Repository\AdminRepository'
  App\Gateway\MemberGateway: '@App\Adapter\Doctrine\Repository\MemberRepository'